plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.gradelens.omr'
version = '0.1.0'

android {
  namespace "com.gradelens.omr"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
    implementation("org.opencv:opencv:4.13.0")
    implementation("org.tensorflow:tensorflow-lite:2.17.0")
}
